/**
 * Mock facilities dataset for local development and production demo fallback.
 * 로컬 개발 및 프로덕션 데모 폴백을 위한 파크골프 시설 모의 데이터셋입니다.
 */
export const MOCK_FACILITIES = [
  {
    id: "seed-facility-jamsil",
    name: "잠실 파크골프장",
    address: "서울특별시 송파구 잠실동 10",
    province: "서울",
    district: "송파구",
    regionKey: "capital",
    facilityType: "outdoor",
    status: "active",
    ownership: "public",
    operatorName: "송파구청",
    phone: "02-423-0045",
    lat: 37.5148406,
    lng: 127.0728795,
    sourceName: "seed",
    sourceUrl: "https://example.com",
    lastCheckedAt: new Date("2026-05-25T00:00:00.000Z"),
    createdAt: new Date("2026-05-25T00:00:00.000Z"),
    updatedAt: new Date("2026-05-25T00:00:00.000Z"),
    pricing: {
      id: "price-jamsil",
      facilityId: "seed-facility-jamsil",
      baseFeeText: "성인 3,000원 / 청소년 2,000원",
      concessionFeeText: "만 65세 이상 어르신 50% 할인 (경로우대) / 50% discount for seniors over 65",
      feeType: "paid",
    },
    reservation: {
      id: "res-jamsil",
      facilityId: "seed-facility-jamsil",
      summary: "인터넷 선착순 · 전화 예약 / Online (FCFS) & Phone",
      methods: [
        {
          id: "m-jamsil-1",
          reservationInfoId: "res-jamsil",
          methodType: "internet_first_come",
          methodText: "송파구 통합예약 사이트 선착순 접수",
          priority: 1,
          ruleText: null,
          url: "https://example.go.kr/booking",
          notes: "매월 25일 오전 9시 다음 달 예약 오픈 / Booking opens at 9 AM on the 25th of every month",
        },
        {
          id: "m-jamsil-2",
          reservationInfoId: "res-jamsil",
          methodType: "phone",
          methodText: "관리사무소 대표번호 전화 문의",
          priority: 2,
          ruleText: null,
          url: null,
          notes: "노약자 및 경로우대 대상자만 전화 예약 가능 / Phone bookings restricted to seniors & disabled",
        },
      ],
    },
  },
  {
    id: "seed-facility-chungju",
    name: "충주 월드 파크골프장",
    address: "충청북도 충주시 호암동 123",
    province: "충북",
    district: "충주시",
    regionKey: "chungcheong",
    facilityType: "outdoor",
    status: "active",
    ownership: "public",
    operatorName: "충주시시설관리공단",
    phone: "043-850-1234",
    lat: 36.958,
    lng: 127.933,
    sourceName: "seed",
    sourceUrl: "https://example.com",
    lastCheckedAt: new Date("2026-05-25T00:00:00.000Z"),
    createdAt: new Date("2026-05-25T00:00:00.000Z"),
    updatedAt: new Date("2026-05-25T00:00:00.000Z"),
    pricing: {
      id: "price-chungju",
      facilityId: "seed-facility-chungju",
      baseFeeText: "무료 이용 가능 / Free Entry",
      concessionFeeText: null,
      feeType: "free",
    },
    reservation: {
      id: "res-chungju",
      facilityId: "seed-facility-chungju",
      summary: "방문 접수 / Walk-in",
      methods: [
        {
          id: "m-chungju-1",
          reservationInfoId: "res-chungju",
          methodType: "visit",
          methodText: "현장 대기 후 선착순 입장",
          priority: 1,
          ruleText: null,
          url: null,
          notes: "주말에는 대기 줄이 길 수 있습니다 / Long queues expected during weekends",
        },
      ],
    },
  },
  {
    id: "seed-facility-daegu",
    name: "대구 불로 파크골프장",
    address: "대구광역시 동구 불로동 99",
    province: "대구",
    district: "동구",
    regionKey: "yeongnam",
    facilityType: "outdoor",
    status: "active",
    ownership: "public",
    operatorName: "대구시체육회",
    phone: "053-987-6543",
    lat: 35.912,
    lng: 128.636,
    sourceName: "seed",
    sourceUrl: "https://example.com",
    lastCheckedAt: new Date("2026-05-25T00:00:00.000Z"),
    createdAt: new Date("2026-05-25T00:00:00.000Z"),
    updatedAt: new Date("2026-05-25T00:00:00.000Z"),
    pricing: {
      id: "price-daegu",
      facilityId: "seed-facility-daegu",
      baseFeeText: "기본 2,000원 / Base fee 2000 KRW",
      concessionFeeText: null,
      feeType: "paid",
    },
    reservation: {
      id: "res-daegu",
      facilityId: "seed-facility-daegu",
      summary: "인터넷 추첨제 / Online Lottery",
      methods: [
        {
          id: "m-daegu-1",
          reservationInfoId: "res-daegu",
          methodType: "internet_lottery",
          methodText: "대구시 예약 통합 포털 내 추첨 신청",
          priority: 1,
          ruleText: null,
          url: "https://example.daegu.go.kr/lottery",
          notes: "매월 1일부터 5일까지 접수 후 7일 발표 / Apply between 1st-5th, drawing on 7th",
        },
      ],
    },
  },
];
